apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  labels:
    app: reverse-words
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: quay.io/karmab/dummy-app:latest
        ports:
        - containerPort: 7000
          name: http
        env:
        - name: DUMMY_URL
          value: "dummy-app-backend.karmab.sysdeseng.com"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy-app
  name: dummy-app
  namespace: default
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: dummy-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dummy-app
spec:
  host: dummy-app-backend.karmab.sysdeseng.com
  to:
    kind: Service
    name: dummy-app
